//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MabiChatSpeech.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("client.exe")]
        public string @__CapureProgram {
            get {
                return ((string)(this["__CapureProgram"]));
            }
            set {
                this["__CapureProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11020")]
        public uint @__CapturePort {
            get {
                return ((uint)(this["__CapturePort"]));
            }
            set {
                this["__CapturePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int @__SaveMode {
            get {
                return ((int)(this["__SaveMode"]));
            }
            set {
                this["__SaveMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string @__SavePath {
            get {
                return ((string)(this["__SavePath"]));
            }
            set {
                this["__SavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ＭＳ Ｐゴシック")]
        public string @__ChatFontName {
            get {
                return ((string)(this["__ChatFontName"]));
            }
            set {
                this["__ChatFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float @__ChatFontSize {
            get {
                return ((float)(this["__ChatFontSize"]));
            }
            set {
                this["__ChatFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int @__ChatFontStyle {
            get {
                return ((int)(this["__ChatFontStyle"]));
            }
            set {
                this["__ChatFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-16711936")]
        public int @__ChatForeColor {
            get {
                return ((int)(this["__ChatForeColor"]));
            }
            set {
                this["__ChatForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-16777216")]
        public int @__ChatBackColor {
            get {
                return ((int)(this["__ChatBackColor"]));
            }
            set {
                this["__ChatBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int @__ChatSelWhitelist {
            get {
                return ((int)(this["__ChatSelWhitelist"]));
            }
            set {
                this["__ChatSelWhitelist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int @__ChatSelUser {
            get {
                return ((int)(this["__ChatSelUser"]));
            }
            set {
                this["__ChatSelUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int @__ChatSelPet {
            get {
                return ((int)(this["__ChatSelPet"]));
            }
            set {
                this["__ChatSelPet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int @__ChatSelNpc {
            get {
                return ((int)(this["__ChatSelNpc"]));
            }
            set {
                this["__ChatSelNpc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool @__ChatFaceEmo {
            get {
                return ((bool)(this["__ChatFaceEmo"]));
            }
            set {
                this["__ChatFaceEmo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int @__TTS1Volume {
            get {
                return ((int)(this["__TTS1Volume"]));
            }
            set {
                this["__TTS1Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int @__TTS1Speed {
            get {
                return ((int)(this["__TTS1Speed"]));
            }
            set {
                this["__TTS1Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int @__TTS2Volume {
            get {
                return ((int)(this["__TTS2Volume"]));
            }
            set {
                this["__TTS2Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int @__TTS2Speed {
            get {
                return ((int)(this["__TTS2Speed"]));
            }
            set {
                this["__TTS2Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool @__TTS_Mute {
            get {
                return ((bool)(this["__TTS_Mute"]));
            }
            set {
                this["__TTS_Mute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool @__TTS_NameCall {
            get {
                return ((bool)(this["__TTS_NameCall"]));
            }
            set {
                this["__TTS_NameCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int @__ChatFontCharSet {
            get {
                return ((int)(this["__ChatFontCharSet"]));
            }
            set {
                this["__ChatFontCharSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool @__ChatFontBold {
            get {
                return ((bool)(this["__ChatFontBold"]));
            }
            set {
                this["__ChatFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool @__ChatFontItalic {
            get {
                return ((bool)(this["__ChatFontItalic"]));
            }
            set {
                this["__ChatFontItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./")]
        public string @__ServerList_Path {
            get {
                return ((string)(this["__ServerList_Path"]));
            }
            set {
                this["__ServerList_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./")]
        public string @__WhiteList_Path {
            get {
                return ((string)(this["__WhiteList_Path"]));
            }
            set {
                this["__WhiteList_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool @__WhiteList_AutoAdd {
            get {
                return ((bool)(this["__WhiteList_AutoAdd"]));
            }
            set {
                this["__WhiteList_AutoAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string @__TTS1Name {
            get {
                return ((string)(this["__TTS1Name"]));
            }
            set {
                this["__TTS1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string @__TTS2Name {
            get {
                return ((string)(this["__TTS2Name"]));
            }
            set {
                this["__TTS2Name"] = value;
            }
        }
    }
}
